include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: ignore
    no_wildcard_variable_uses: ignore
    prefer_const_constructors: ignore
    prefer_final_fields: ignore
